services:
  cassandra:
    image: "cassandra:4.1.8"
    container_name: cassandra
    hostname: cassandra
    restart: unless-stopped
    user: ${UID}:${GID}
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_NUM_TOKENS=4
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
    volumes:
      - csdata:/var/lib/cassandra
      - cslogs:/var/log/cassandra
    deploy:
      resources:
        limits:
          memory: 1G
    # Prevent swap https://docs.docker.com/engine/containers/resource_constraints/#prevent-a-container-from-using-swap
    memswap_limit: 1G
    networks:
      - thehive-network
    healthcheck:
      # Waiting for cqlsh command to succeed to make sure Cassandra is ready
      test: ["CMD-SHELL", "cqlsh -u cassandra -p cassandra -e 'describe keyspaces' || exit 1"]
      start_period: 120s
      interval: 2s
      timeout: 1s
      retries: 3
    labels:
      com.strangebee.stack: "thehive-stack"
      com.strangebee.service: "cassandra"
      com.strangebee.role: "database"
      com.strangebee.environment: "testing"
      com.strangebee.version: "4.1.8"
      com.strangebee.dependency: "None"

  elasticsearch:
    image: "elasticsearch:7.17.10"
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    user: ${UID}:0
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=100000
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${elasticsearch_password} # Password for "elastic" default user
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - eslogs:/usr/share/elasticsearch/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 512M
    memswap_limit: 512M
    networks:
      - thehive-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -u 'elastic:${elasticsearch_password}' http://elasticsearch:9200/_cat/health || exit 1"]
      start_period: 40s
      interval: 2s
      timeout: 1s
      retries: 5
    labels:
      com.strangebee.stack: "thehive-stack"
      com.strangebee.service: "elasticsearch"
      com.strangebee.role: "indexing"
      com.strangebee.environment: "testing"
      com.strangebee.version: "7.17.10"
      com.strangebee.dependency: "None"

  thehive:
    image: "strangebee/thehive:5"
    container_name: thehive
    hostname: thehive
    restart: unless-stopped
    #command: '--no-config --no-config-secret'
    user: ${UID}:${GID}
    environment:
      - |
        JAVA_OPTS=
          -Xms512M
          -Xmx512M
          -XX:MaxMetaspaceSize=256m
          -XX:ReservedCodeCacheSize=128m
    volumes:
      - ./config:/etc/thehive:ro
      - thehive_data:/opt/thp/thehive/files
      - thehive_logs:/var/log/thehive
    deploy:
      resources:
        limits:
          memory: 1G
    memswap_limit: 1G
    networks:
      - thehive-network
    ports:
      - '0.0.0.0:9000:9000'
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f thehive:9000/thehive/api/status || exit 1"]
      start_period: 40s
      interval: 10s
      timeout: 1s
      retries: 5
    depends_on:
      elasticsearch:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    labels:
      com.strangebee.stack: "thehive-stack"
      com.strangebee.service: "thehive"
      com.strangebee.role: "application"
      com.strangebee.environment: "testing"
      com.strangebee.version: "5"
      com.strangebee.dependency: "elasticsearch, cassandra"

networks:
  thehive-network:

volumes:
  csdata:
  cslogs:
  esdata:
  eslogs:
  thehive_data:
  thehive_logs:
